const LIBERTAIRE_DATA = [
  {
    "id": 1,
    "page": 1,
    "organisation": "Organisation Anarchiste (OA)",
    "nom": "Groupe Puig Antich",
    "ville": "Perpignan",
    "contact": "contact@groupe-puig-antich.info",
    "adresse": "Librairie Infos, 2 rue Théodore Guiter",
    "type": "Groupe",
    "lat": 42.6986,
    "lng": 2.8956
  },
  {
    "id": 2,
    "page": 1,
    "organisation": "Organisation Anarchiste (OA)",
    "nom": "Groupe Albert Camus",
    "ville": "Toulouse",
    "contact": "groupe.albert.camus@gmail.com",
    "adresse": "36 rue de Cugnaux, 31300 Toulouse",
    "type": "Groupe",
    "lat": 43.6047,
    "lng": 1.4442
  },
  {
    "id": 3,
    "page": 1,
    "organisation": "Organisation Anarchiste (OA)",
    "nom": "Groupe Anarchiste de Carcassonne",
    "ville": "Carcassonne",
    "contact": "groupecarcassonne@gmail.com",
    "adresse": "—",
    "type": "Groupe",
    "lat": 43.2122,
    "lng": 2.3537
  },
  {
    "id": 4,
    "page": 1,
    "organisation": "Organisation Anarchiste (OA)",
    "nom": "Liaison Région parisienne",
    "ville": "Région parisienne / 93",
    "contact": "oa@infosetanalyseslibertaires.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 48.91,
    "lng": 2.45
  },
  {
    "id": 5,
    "page": 1,
    "organisation": "Organisation Anarchiste (OA)",
    "nom": "Liaison du Gers",
    "ville": "Auch / Gers",
    "contact": "oa@infosetanalyseslibertaires.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 43.6464,
    "lng": 0.5857
  },
  {
    "id": 6,
    "page": 1,
    "organisation": "Organisation Anarchiste (OA)",
    "nom": "Liaison Orléans",
    "ville": "Orléans",
    "contact": "oa@infosetanalyseslibertaires.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 47.903,
    "lng": 1.9093
  },
  {
    "id": 7,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Nomade La Roulotte Noire",
    "ville": "Nomade",
    "contact": "groupe-nomade@federation-anarchiste.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 46.603354,
    "lng": 1.888334
  },
  {
    "id": 8,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Kropotkine",
    "ville": "Aisne / Merlieux",
    "contact": "kropotkine02@riseup.net",
    "adresse": "Athénée Le Loup Noir, 8 rue Fouquerolles, 02000 Merlieux",
    "type": "Groupe",
    "lat": 49.5218,
    "lng": 3.5415
  },
  {
    "id": 9,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison Étoile Noire",
    "ville": "Allier",
    "contact": "etoile-noire@federation-anarchiste.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 46.34,
    "lng": 3.14
  },
  {
    "id": 10,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe d'Aubenas",
    "ville": "Ardèche",
    "contact": "fa-groupe-daubenas@wanadoo.fr",
    "adresse": "—",
    "type": "Groupe",
    "lat": 44.75,
    "lng": 4.4
  },
  {
    "id": 11,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe La Chèvre Noire",
    "ville": "Ardèche",
    "contact": "groupe-lachevrenoire@federation-anarchiste.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 44.75,
    "lng": 4.4
  },
  {
    "id": 12,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison Ariège",
    "ville": "Ariège",
    "contact": "ariege@federation-anarchiste.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 42.9,
    "lng": 1.4
  },
  {
    "id": 13,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison Sud-Aveyron",
    "ville": "Aveyron",
    "contact": "sud-aveyron@federation-anarchiste.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 44.15,
    "lng": 2.6
  },
  {
    "id": 14,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison La Ciotat",
    "ville": "Bouches-du-Rhône",
    "contact": "liaison-la-ciotat@federation-anarchiste.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 43.5,
    "lng": 5.2
  },
  {
    "id": 15,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Oaï",
    "ville": "Marseille",
    "contact": "oai@federation-anarchiste.org",
    "adresse": "Marseille",
    "type": "Groupe",
    "lat": 43.2965,
    "lng": 5.3698
  },
  {
    "id": 16,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Emma Goldman",
    "ville": "Périgueux",
    "contact": "perigueux@federation-anarchiste.org",
    "adresse": "Périgueux",
    "type": "Groupe",
    "lat": 45.1847,
    "lng": 0.7217
  },
  {
    "id": 17,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Pierre Joseph Proudhon",
    "ville": "Besançon",
    "contact": "groupe-proudhon@federation-anarchiste.org",
    "adresse": "c/o CESL BP 121, 25014 Besançon Cedex",
    "type": "Groupe",
    "lat": 47.2378,
    "lng": 6.0241
  },
  {
    "id": 18,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Le Ferment",
    "ville": "Finistère",
    "contact": "leferment@federation-anarchiste.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 48.15,
    "lng": -4.1
  },
  {
    "id": 19,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Nathalie Le Mel",
    "ville": "Finistère",
    "contact": "nathalie-le-mel@federation-anarchiste.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 48.15,
    "lng": -4.1
  },
  {
    "id": 20,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Son of Anarchy 34",
    "ville": "Hérault",
    "contact": "sonofanarchy34@federation-anarchiste.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 43.6,
    "lng": 3.5
  },
  {
    "id": 21,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe La Sociale",
    "ville": "Rennes",
    "contact": "contact@falasociale.org",
    "adresse": "c/o Local La Commune, 17 rue de Châteaudun, 35000 Rennes",
    "type": "Groupe",
    "lat": 48.1173,
    "lng": -1.6778
  },
  {
    "id": 22,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Nestor Makhno",
    "ville": "Saint-Étienne",
    "contact": "groupe.makhno42@gmail.com",
    "adresse": "Bourse du Travail, salle 15 bis, cours Victor Hugo, 42028 Saint-Étienne Cedex 1",
    "type": "Groupe",
    "lat": 45.4397,
    "lng": 4.3872
  },
  {
    "id": 23,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe René Lochu",
    "ville": "Vannes",
    "contact": "groupe.lochu@riseup.net",
    "adresse": "Maison des associations, 31 rue Guillaume Le Bartz, 56000 Vannes",
    "type": "Groupe",
    "lat": 47.6586,
    "lng": -2.7599
  },
  {
    "id": 24,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Salvador Segui",
    "ville": "Paris",
    "contact": "groupsalvadorsegui@gmail.com",
    "adresse": "—",
    "type": "Groupe",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 25,
    "page": 1,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Pierre Besnard",
    "ville": "Paris",
    "contact": "pierre-besnard@outlook.fr",
    "adresse": "145 rue Amelot, 75011 Paris",
    "type": "Groupe",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 26,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Commune de Paris",
    "ville": "Paris",
    "contact": "commune-de-paris@federation-anarchiste.org",
    "adresse": "145 rue Amelot, 75011 Paris",
    "type": "Groupe",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 27,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe La Révolte",
    "ville": "Paris",
    "contact": "la-revolte@federation-anarchiste.org",
    "adresse": "145 rue Amelot, 75011 Paris",
    "type": "Groupe",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 28,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Louise Michel",
    "ville": "Paris",
    "contact": "groupe-louise-michel@federation-anarchiste.org",
    "adresse": "145 rue Amelot, 75011 Paris",
    "type": "Groupe",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 29,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe de Rouen",
    "ville": "Rouen",
    "contact": "rouen@federation-anarchiste.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 49.4432,
    "lng": 1.0999
  },
  {
    "id": 30,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Henry Poulaille",
    "ville": "Saint-Denis",
    "contact": "groupe-henry-poulaille@wanadoo.fr",
    "adresse": "c/o La Dionyversité, 4 place Paul Langevin, 93200 Saint-Denis",
    "type": "Groupe",
    "lat": 48.9362,
    "lng": 2.3574
  },
  {
    "id": 31,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe libertaire d'Ivry",
    "ville": "Ivry-sur-Seine",
    "contact": "ivry@anarchiste.info",
    "adresse": "—",
    "type": "Groupe",
    "lat": 48.8153,
    "lng": 2.3875
  },
  {
    "id": 32,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison Poitiers",
    "ville": "Poitiers",
    "contact": "poitiers@federation-anarchiste.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 46.5802,
    "lng": 0.3404
  },
  {
    "id": 33,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison Haute-Saône",
    "ville": "Haute-Saône",
    "contact": "liaison.haute-saone@federation-anarchiste.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 47.6333,
    "lng": 6.15
  },
  {
    "id": 34,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison La Vache Noire",
    "ville": "Mâcon / Saône-et-Loire",
    "contact": "lavachenoire@le-local-libertaire.com",
    "adresse": "399 quai Jean Jaurès, 71000 Mâcon",
    "type": "Liaison",
    "lat": 46.3069,
    "lng": 4.8317
  },
  {
    "id": 35,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison Bas-Rhin",
    "ville": "Bas-Rhin",
    "contact": "liaison-bas-rhin@federation-anarchiste.org",
    "adresse": "c/o REMON BP 35, 67340 Ingwiller",
    "type": "Liaison",
    "lat": 48.7,
    "lng": 7.6
  },
  {
    "id": 36,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison Commune de Lyon",
    "ville": "Lyon",
    "contact": "communedelyon@federation-anarchiste.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 45.764,
    "lng": 4.8357
  },
  {
    "id": 37,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison Evry-Corbeil",
    "ville": "Essonne",
    "contact": "evry-corbeil@federation-anarchiste.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 48.5,
    "lng": 2.3
  },
  {
    "id": 38,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Liaison 87",
    "ville": "Haute-Vienne",
    "contact": "liaisonfa87@proton.me",
    "adresse": "—",
    "type": "Liaison",
    "lat": 45.8,
    "lng": 1.25
  },
  {
    "id": 39,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Les ELAFF",
    "ville": "Tarn",
    "contact": "elaf@federation-anarchiste.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 43.9,
    "lng": 2.15
  },
  {
    "id": 40,
    "page": 2,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Henri Laborit",
    "ville": "Vendée",
    "contact": "henri-laborit@federation-anarchiste.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 46.67,
    "lng": -1.43
  },
  {
    "id": 41,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Ain",
    "ville": "Ain",
    "contact": "ucl-ain@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 46.1,
    "lng": 5.3
  },
  {
    "id": 42,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Clermont-Ferrand",
    "ville": "Clermont-Ferrand",
    "contact": "ucl-clermont-ferrand@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 45.7772,
    "lng": 3.087
  },
  {
    "id": 43,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Grenoble",
    "ville": "Grenoble",
    "contact": "ucl-grenoble@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 45.1885,
    "lng": 5.7245
  },
  {
    "id": 44,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Le Puy-en-Velay",
    "ville": "Le Puy-en-Velay",
    "contact": "ucl-lepuyenvelay@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 45.0428,
    "lng": 3.8829
  },
  {
    "id": 45,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Lyon",
    "ville": "Lyon",
    "contact": "ucl-lyon@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 45.764,
    "lng": 4.8357
  },
  {
    "id": 46,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Saint-Étienne",
    "ville": "Saint-Étienne",
    "contact": "ucl-saint-etienne@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 45.4397,
    "lng": 4.3872
  },
  {
    "id": 47,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Savoies",
    "ville": "Savoie",
    "contact": "ucl_chambery.savoie@inventati.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 45.55,
    "lng": 6.5
  },
  {
    "id": 48,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Alpes-Provence",
    "ville": "Alpes-Provence",
    "contact": "ucl-alpesprovence@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 44.0,
    "lng": 6.0
  },
  {
    "id": 49,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Marseille",
    "ville": "Marseille",
    "contact": "ucl-marseille@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 43.2965,
    "lng": 5.3698
  },
  {
    "id": 50,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Aix-en-Provence / liaison Marseille",
    "ville": "Aix-en-Provence",
    "contact": "ucl-aix-en-pce@communisteslibertaires.org",
    "adresse": "—",
    "type": "Liaison",
    "lat": 43.5297,
    "lng": 5.4474
  },
  {
    "id": 51,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Var / Toulon",
    "ville": "Var / Toulon",
    "contact": "ucl-var@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe / liaison",
    "lat": 43.1242,
    "lng": 5.928
  },
  {
    "id": 52,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Angers",
    "ville": "Angers",
    "contact": "ucl-angers@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 47.4784,
    "lng": -0.5632
  },
  {
    "id": 53,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Nantes",
    "ville": "Nantes",
    "contact": "ucl-nantes@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 47.2184,
    "lng": -1.5536
  },
  {
    "id": 54,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Sarthe",
    "ville": "Sarthe",
    "contact": "ucl-sarthe@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 48.0,
    "lng": 0.2
  },
  {
    "id": 55,
    "page": 2,
    "organisation": "UCL",
    "nom": "UCL Dordogne",
    "ville": "Dordogne",
    "contact": "ucl-dordogne@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 45.15,
    "lng": 0.7
  },
  {
    "id": 56,
    "page": 3,
    "organisation": "UCL",
    "nom": "UCL Limousin",
    "ville": "Limousin",
    "contact": "ucl-limousin@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 45.8,
    "lng": 1.7
  },
  {
    "id": 57,
    "page": 3,
    "organisation": "UCL",
    "nom": "UCL Banlieue Sud-Est",
    "ville": "Île-de-France",
    "contact": "ucl-bse@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 48.8499,
    "lng": 2.637
  },
  {
    "id": 58,
    "page": 3,
    "organisation": "UCL",
    "nom": "UCL Montreuil",
    "ville": "Montreuil",
    "contact": "ucl-montreuil@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 48.8638,
    "lng": 2.4484
  },
  {
    "id": 59,
    "page": 3,
    "organisation": "UCL",
    "nom": "UCL Paris Nord-Est",
    "ville": "Paris",
    "contact": "ucl-paris-nordest@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 60,
    "page": 3,
    "organisation": "UCL",
    "nom": "UCL Saint-Denis",
    "ville": "Saint-Denis",
    "contact": "ucl-saint-denis@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 48.9362,
    "lng": 2.3574
  },
  {
    "id": 61,
    "page": 3,
    "organisation": "UCL",
    "nom": "UCL Dijon",
    "ville": "Dijon",
    "contact": "ucl-dijon@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 47.322,
    "lng": 5.0415
  },
  {
    "id": 62,
    "page": 3,
    "organisation": "OCL",
    "nom": "Organisation communiste libertaire",
    "ville": "Reims",
    "contact": "oclibertaire@hotmail.com",
    "adresse": "OCL c/o Égrégore, BP 1213, 51058 Reims Cedex",
    "type": "Organisation",
    "lat": 49.2583,
    "lng": 4.0317
  },
  {
    "id": 63,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "CNT-AIT Anational",
    "ville": "Toulouse",
    "contact": "contact@cnt-ait.info",
    "adresse": "7 rue Saint-Rémésy, 31000 Toulouse",
    "type": "Organisation",
    "lat": 43.6047,
    "lng": 1.4442
  },
  {
    "id": 64,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "Paris / Banlieue",
    "ville": "Île-de-France",
    "contact": "contact@cnt-ait.info",
    "adresse": "—",
    "type": "Section / groupe",
    "lat": 48.8499,
    "lng": 2.637
  },
  {
    "id": 65,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "Montauban / Quercy-Rouergue",
    "ville": "Montauban",
    "contact": "montauban@cnt-ait.info",
    "adresse": "—",
    "type": "Section / groupe",
    "lat": 44.0175,
    "lng": 1.355
  },
  {
    "id": 66,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "Sud-Ouest",
    "ville": "Toulouse / Sud-Ouest",
    "contact": "toulouse@cntaittoulouse.lautre.net",
    "adresse": "—",
    "type": "Section / groupe",
    "lat": 43.6047,
    "lng": 1.4442
  },
  {
    "id": 67,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "Grand-Ouest",
    "ville": "Bretagne / Pays de la Loire",
    "contact": "ingo-cntait@revlibertaire.com",
    "adresse": "—",
    "type": "Section / groupe",
    "lat": 48.0,
    "lng": -2.0
  },
  {
    "id": 68,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "Allier",
    "ville": "Allier",
    "contact": "initiative.03@cnt-ait.info",
    "adresse": "—",
    "type": "Section / groupe",
    "lat": 46.34,
    "lng": 3.14
  },
  {
    "id": 69,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "Aveyron",
    "ville": "Aveyron",
    "contact": "aveyron@cnt-ait.info",
    "adresse": "—",
    "type": "Section / groupe",
    "lat": 44.15,
    "lng": 2.6
  },
  {
    "id": 70,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "Perpignan / Pyrénées-Orientales",
    "ville": "Perpignan",
    "contact": "perpignan@cnt-ait.info",
    "adresse": "—",
    "type": "Section / groupe",
    "lat": 42.6986,
    "lng": 2.8956
  },
  {
    "id": 71,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "Nord / Est",
    "ville": "Nord / Est",
    "contact": "contact@cnt-ait.info",
    "adresse": "—",
    "type": "Section / groupe",
    "lat": 50.0,
    "lng": 3.0
  },
  {
    "id": 72,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "Centre",
    "ville": "Centre",
    "contact": "contact@cnt-ait.info",
    "adresse": "—",
    "type": "Section / groupe",
    "lat": 47.5,
    "lng": 1.7
  },
  {
    "id": 73,
    "page": 3,
    "organisation": "CNT-AIT",
    "nom": "Normandie",
    "ville": "Normandie",
    "contact": "contact@cnt-ait.info",
    "adresse": "—",
    "type": "Section / groupe",
    "lat": 49.0,
    "lng": 0.3
  },
  {
    "id": 74,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Confédération nationale du travail",
    "ville": "Paris",
    "contact": "Viacnt-f.org",
    "adresse": "33 rue des Vignoles, 75020 Paris",
    "type": "Organisation",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 75,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Union régionale parisienne",
    "ville": "Paris / Île-de-France",
    "contact": "br.rp@cnt-f.org",
    "adresse": "33 rue des Vignoles, 75020 Paris",
    "type": "Union régionale",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 76,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Union locale de Toulouse (CNT 31)",
    "ville": "Toulouse",
    "contact": "is.31@cnt-f.org",
    "adresse": "Au Chat Noir, 270 avenue de Muret, 31300 Toulouse",
    "type": "Union locale",
    "lat": 43.6047,
    "lng": 1.4442
  },
  {
    "id": 77,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Union régionale Midi-Pyrénées",
    "ville": "Toulouse / Midi-Pyrénées",
    "contact": "midipyrenees@cnt-f.org",
    "adresse": "Au Chat Noir, 270 avenue de Muret, 31300 Toulouse",
    "type": "Union régionale",
    "lat": 43.6047,
    "lng": 1.4442
  },
  {
    "id": 78,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Union départementale de Gironde (CNT 33)",
    "ville": "Bordeaux",
    "contact": "Viaul33.cnt-f.org",
    "adresse": "36 rue Sanche-de-Pomiers, 33000 Bordeaux",
    "type": "Union locale",
    "lat": 44.8378,
    "lng": -0.5792
  },
  {
    "id": 79,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Union locale de Nantes (interco 44)",
    "ville": "Nantes",
    "contact": "interco44@cnt-f.org",
    "adresse": "B17, 17 rue Paul Bellamy, 44000 Nantes",
    "type": "Union locale",
    "lat": 47.2184,
    "lng": -1.5536
  },
  {
    "id": 80,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Union locale de Saint-Étienne (CNT 42)",
    "ville": "Saint-Étienne",
    "contact": "cnt42@cnt-f.org",
    "adresse": "Bourse du Travail, salle 15 bis, cours Victor Hugo, 42028 Saint-Étienne Cedex 1",
    "type": "Union locale",
    "lat": 45.4397,
    "lng": 4.3872
  },
  {
    "id": 81,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Union locale de Rennes (CNT 35)",
    "ville": "Rennes",
    "contact": "Via35.cnt-f.org",
    "adresse": "BP 30423, 35004 Rennes Cedex",
    "type": "Union locale",
    "lat": 48.1173,
    "lng": -1.6778
  },
  {
    "id": 82,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Union régionale Rhône-Alpes / UD Rhône",
    "ville": "Lyon",
    "contact": "Viacnt-f.org/cnt69",
    "adresse": "44 rue Burdeau, 69001 Lyon",
    "type": "Union régionale",
    "lat": 45.764,
    "lng": 4.8357
  },
  {
    "id": 83,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Union locale de Lille (SSEC 59-62)",
    "ville": "Lille",
    "contact": "ssec5962@cnt-f.org",
    "adresse": "32 rue d'Arras, 59000 Lille",
    "type": "Union locale",
    "lat": 50.6292,
    "lng": 3.0573
  },
  {
    "id": 84,
    "page": 3,
    "organisation": "CNT-F / Vignoles",
    "nom": "Syndicat interprofessionnel de Strasbourg (67)",
    "ville": "Strasbourg",
    "contact": "interpro67@cnt-f.org",
    "adresse": "Maison des syndicats, 1 rue Sedillot, 67000 Strasbourg",
    "type": "Union locale",
    "lat": 48.5734,
    "lng": 7.7521
  },
  {
    "id": 85,
    "page": 3,
    "organisation": "CNT-SO",
    "nom": "CNT-Solidarité Ouvrière",
    "ville": "Paris",
    "contact": "Viacnt-so.org",
    "adresse": "Contact national",
    "type": "Organisation",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 86,
    "page": 4,
    "organisation": "CNT-SO",
    "nom": "Permanence Île-de-France",
    "ville": "Île-de-France",
    "contact": "contact@cnt-so.org",
    "adresse": "Permanence sur RDV",
    "type": "Permanence",
    "lat": 48.8499,
    "lng": 2.637
  },
  {
    "id": 87,
    "page": 4,
    "organisation": "CNT-SO",
    "nom": "Permanence Bouches-du-Rhône (13)",
    "ville": "Marseille",
    "contact": "contact13@cnt-so.org",
    "adresse": "24-28 rue abbé Féraud, 13005 Marseille",
    "type": "Permanence",
    "lat": 43.2965,
    "lng": 5.3698
  },
  {
    "id": 88,
    "page": 4,
    "organisation": "CNT-SO",
    "nom": "Union départementale du Rhône (69)",
    "ville": "Villeurbanne / Lyon",
    "contact": "ud69@cnt-so.org",
    "adresse": "8 rue Paul Lafargue, 69100 Villeurbanne",
    "type": "Permanence",
    "lat": 45.7667,
    "lng": 4.8833
  },
  {
    "id": 89,
    "page": 4,
    "organisation": "CNT-SO",
    "nom": "Permanence Auvergne",
    "ville": "Auvergne",
    "contact": "auvergne@cnt-so.org",
    "adresse": "—",
    "type": "Permanence",
    "lat": 45.5,
    "lng": 3.0
  },
  {
    "id": 90,
    "page": 4,
    "organisation": "CNT-SO",
    "nom": "Permanence Poitou-Charentes",
    "ville": "Poitiers",
    "contact": "poitoucharentes@cnt-so.org",
    "adresse": "—",
    "type": "Permanence",
    "lat": 46.5802,
    "lng": 0.3404
  },
  {
    "id": 91,
    "page": 4,
    "organisation": "CNT-SO",
    "nom": "Permanence Aquitaine",
    "ville": "Aquitaine (24-33-40-47-64)",
    "contact": "aquitaine@cnt-so.org",
    "adresse": "—",
    "type": "Permanence",
    "lat": 44.5,
    "lng": -0.5
  },
  {
    "id": 92,
    "page": 4,
    "organisation": "CNT-SO",
    "nom": "STAA — Syndicat des travailleur.euse.s artistes-auteur.ice.s",
    "ville": "Paris",
    "contact": "contact@staa-cnt-so.org",
    "adresse": "—",
    "type": "Fédération",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 93,
    "page": 4,
    "organisation": "Indépendant / local",
    "nom": "Athénée libertaire",
    "ville": "Bordeaux",
    "contact": "—",
    "adresse": "7 rue du Muguet, 33000 Bordeaux",
    "type": "Local",
    "lat": 44.8378,
    "lng": -0.5792
  },
  {
    "id": 94,
    "page": 4,
    "organisation": "Indépendant / local",
    "nom": "Le Loup Noir",
    "ville": "Merlieux",
    "contact": "—",
    "adresse": "8 rue de Fouquerolles, 02000 Merlieux",
    "type": "Local",
    "lat": 49.5218,
    "lng": 3.5415
  },
  {
    "id": 95,
    "page": 4,
    "organisation": "Indépendant / local",
    "nom": "B17",
    "ville": "Nantes",
    "contact": "—",
    "adresse": "17 rue Paul Bellamy, 44000 Nantes",
    "type": "Local",
    "lat": 47.2184,
    "lng": -1.5536
  },
  {
    "id": 96,
    "page": 4,
    "organisation": "Indépendant / local",
    "nom": "Le 102",
    "ville": "Grenoble",
    "contact": "—",
    "adresse": "102 rue d'Alembert, 38000 Grenoble",
    "type": "Local",
    "lat": 45.1885,
    "lng": 5.7245
  },
  {
    "id": 97,
    "page": 4,
    "organisation": "Indépendant / local",
    "nom": "Mille Bâbords",
    "ville": "Marseille",
    "contact": "—",
    "adresse": "61 rue Consolat, 13001 Marseille",
    "type": "Local",
    "lat": 43.2965,
    "lng": 5.3698
  },
  {
    "id": 98,
    "page": 4,
    "organisation": "Indépendant / local",
    "nom": "Molodoï",
    "ville": "Strasbourg",
    "contact": "info@molodoi.net",
    "adresse": "19 rue du Ban de la Roche, 67000 Strasbourg",
    "type": "Local",
    "lat": 48.5734,
    "lng": 7.7521
  },
  {
    "id": 99,
    "page": 4,
    "organisation": "Indépendant / local",
    "nom": "Quilombo",
    "ville": "Paris",
    "contact": "quilombo@globnet.org",
    "adresse": "21 ter rue Voltaire, 75011 Paris",
    "type": "Librairie",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "id": 100,
    "page": 4,
    "organisation": "Indépendant / local",
    "nom": "Jules Durand",
    "ville": "Le Havre",
    "contact": "julesdurand.lehavre@gmail.com",
    "adresse": "Groupe d'Études Sociales du Havre et environs — BP 411, 76057 Le Havre Cedex",
    "type": "Collectif",
    "lat": 49.4944,
    "lng": 0.1079
  },
  {
    "id": 101,
    "page": 4,
    "organisation": "Fédération anarchiste (FA)",
    "nom": "Groupe Ici et Maintenant",
    "ville": "Belgique",
    "contact": "groupe-ici-et-maintenant@federation-anarchiste.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 50.5039,
    "lng": 4.4699
  },
  {
    "id": 102,
    "page": 4,
    "organisation": "UCL",
    "nom": "UCL Bruxelles",
    "ville": "Bruxelles",
    "contact": "ucl-bruxelles@communisteslibertaires.org",
    "adresse": "—",
    "type": "Groupe",
    "lat": 50.8503,
    "lng": 4.3517
  },
  {
    "id": 103,
    "page": 4,
    "organisation": "Indépendant / local (Belgique)",
    "nom": "Anarchistisch Collectief Antwerpen (ACA)",
    "ville": "Anvers",
    "contact": "info@acollectiefantwerpen.be",
    "adresse": "—",
    "type": "Collectif",
    "lat": 51.2194,
    "lng": 4.4025
  },
  {
    "id": 104,
    "page": 4,
    "organisation": "Indépendant / local (Belgique)",
    "nom": "Anarchistisch Collectief Brugge",
    "ville": "Bruges",
    "contact": "anarchistischcollectiefbrugge@protonmail.com",
    "adresse": "—",
    "type": "Collectif",
    "lat": 51.2093,
    "lng": 3.2247
  },
  {
    "id": 105,
    "page": 4,
    "organisation": "Indépendant / local (Belgique)",
    "nom": "Vrij Collectief Kortrijk",
    "ville": "Courtrai",
    "contact": "vrijcollectiefkortrijk@proton.me",
    "adresse": "—",
    "type": "Collectif",
    "lat": 50.828,
    "lng": 3.265
  },
  {
    "id": 106,
    "page": 4,
    "organisation": "Indépendant / local (Belgique)",
    "nom": "Leuvense Anarchistische Groep (LAG)",
    "ville": "Louvain",
    "contact": "leuvenseag@riseup.net",
    "adresse": "—",
    "type": "Groupe",
    "lat": 50.8798,
    "lng": 4.7005
  },
  {
    "id": 107,
    "page": 4,
    "organisation": "Indépendant / local (Belgique)",
    "nom": "Ligue Libre / Vrije Bond Belgique",
    "ville": "Belgique",
    "contact": "contact.belgie@vrijebond.nl",
    "adresse": "—",
    "type": "Liaison",
    "lat": 50.5039,
    "lng": 4.4699
  },
  {
    "id": 108,
    "page": 4,
    "organisation": "Indépendant / local (Belgique)",
    "nom": "Anarchistische Boekenbeurs Gent",
    "ville": "Gand",
    "contact": "abgent@riseup.net",
    "adresse": "—",
    "type": "Collectif",
    "lat": 51.0543,
    "lng": 3.7174
  },
  {
    "id": 109,
    "page": 4,
    "organisation": "Indépendant / local (Belgique)",
    "nom": "Anarchief Gent",
    "ville": "Gand",
    "contact": "info@anarchief.be",
    "adresse": "—",
    "type": "Local",
    "lat": 51.0543,
    "lng": 3.7174
  },
  {
    "id": 110,
    "page": 4,
    "organisation": "Indépendant / local (Belgique)",
    "nom": "La B.O.U.M. — Bibliothèque anarchiste",
    "ville": "Bruxelles",
    "contact": "bibli-anar-bxl@proton.me",
    "adresse": "—",
    "type": "Librairie",
    "lat": 50.8503,
    "lng": 4.3517
  },
  {
    "id": 111,
    "page": 4,
    "organisation": "Indépendant / local (Belgique)",
    "nom": "Stuut — collectif anarchiste/autonome",
    "ville": "Bruxelles",
    "contact": "contact@stuut.info",
    "adresse": "—",
    "type": "Collectif",
    "lat": 50.8503,
    "lng": 4.3517
  }
];