

services:
  repertoire-libertaire:
    image: liberchat/repertoire-libertaire:latest
    build: .
    container_name: repertoire_libertaire_cnt_ait
    ports:
      - "1936:80"
    restart: unless-stopped
